//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiPaginacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public int PROD_ID { get; set; }
        public string PNAME { get; set; }
        public string PDESC { get; set; }
        public Nullable<int> ALMACEN { get; set; }
    }
}
